### ISSUE TITLE
Future enhancements

### ISSUE THREAD

**Issue by rogervila** [rogervila/php-sonarqube-scanner#1]
# Parse arguments

```php
// sonar-scanner
$app->run($argv);

// src/App.php

public function run(array $arguments)
    {
        // TODO: parse arguments, in order to be able to modify the version and the properties path
...
```

**Comment by mercuriete** [comment]
Hi
I want to propose the usage if

SONAR_TOKEN

Environmental variable.

Behaviour:
If that variable is set,
Then -Dsonar.login=SONAR_TOKEN should be passed to the scanner

**Comment by mercuriete** [comment]
Hi
I want yo propose...

Get branch name from git branch....
And set -Dsonar.branch.name

**Comment by mercuriete** [comment]
Hi
I want to propose...
Parse the name of the project from composer.json and then
Use as -Dsonar.projectKey

**Comment by mercuriete** [comment]
Hi
I want to propose...
If there is no unit test XML...

Rerun phpunit with XML output and then upload them with sonar

**Comment by rogervila** [comment]
> Get branch name from git branch....
> And set -Dsonar.branch.name

> Parse the name of the project from composer.json and then

This sould be passed as an argument

```php
sonar-scanner --config=options.php
```
Inside `options.php`
```php
return [
  'automatic-branch-name' => true,
  'project-key-from-composer' => true,
];
```

**Comment by rogervila** [comment]
@mercuriete some properties are dynamically parsed on the first version of this project. 
https://github.com/rogervila/php-sonarqube-scanner/pull/3

More properties will be set on version 1.0

**Comment by mercuriete** [comment]
LOL!
you closed me this bug.
I hate you. xD

**Comment by rogervila** [comment]
@mercuriete I moved the requests to https://github.com/rogervila/php-sonarqube-scanner/issues/4 xD

**Comment by mercuriete** [comment]
@rogervila hahahahaha,

Please reference this issue from the pull request for having both linked.

oh, you dont have any pull request..... very bad!!!!
xD
