### ISSUE TITLE
Scan this project with your own scanner

### ISSUE THREAD

**Issue by mercuriete** [rogervila/php-sonarqube-scanner#8]
Scan your proyect with your project sonnar scaner from composer

**Comment by rogervila** [comment]
I indeed do it on my local environment but, for now, I prefer to keep the CI with Travis and Sonarcloud, while I focus on writing tests before I tag v1

**Comment by mercuriete** [comment]
Nice job!

**Comment by rogervila** [comment]
I have created a test project that uses the scanner with Composer. 

Is not what the issue asks for, but it's something: https://github.com/rogervila/php-sonarqube-scanner-test

**Comment by mercuriete** [comment]
That project doesn't have badge. XD

**Comment by mercuriete** [comment]
@rogervila 
Please add badge to README

**Comment by mercuriete** [comment]
I think this issue can be closed. @rogervila

**Comment by rogervila** [comment]
Thanks @mercuriete
