### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by robsontenorio** [rogervila/php-sonarqube-scanner#9]
Is there any minimal requirements ?

I am running a docker image with PHP

```bash
bash-4.4$ php -v
PHP 7.2.13 (cli) (built: Dec  7 2018 16:36:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies
```

And just added openjdk8-jre.

```bash
bash-4.4$ java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (IcedTea 3.11.0) (Alpine 8.201.08-r0)
OpenJDK 64-Bit Server VM (build 25.201-b08, mixed mode)
```

But i am getting

```bash
bash-4.4$ ./vendor/bin/sonar-scanner 
Asking for executable permissions...
Running scanner...
INFO: /var/www/api/vendor/rogervila/php-sonarqube-scanner/src/../tmp/sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.projectName=myproject-api -Dsonar.projectDescription="My project"
Error relocating /var/www/api/vendor/rogervila/php-sonarqube-scanner/tmp/sonar-scanner-3.3.0.1492-linux/jre/bin/../lib/amd64/jli/libjli.so: __rawmemchr: symbol not found
```

**Comment by rogervila** [comment]
Hello @robsontenorio 
I made a quick test with the official Docker PHP image and it works.

You can download the test project ([sonarqube-test.zip](https://github.com/rogervila/php-sonarqube-scanner/files/3042459/sonarqube-test.zip)) and try it on your environment.

The package itself requires the PHP zip extension, and its set on the composer file so I assume that you have it installed.

Can you share your Dockerfile?

**Comment by mercuriete** [comment]
https://docs.sonarqube.org/plugins/servlet/mobile?contentId=6954796#content/view/6954796

"This package expects that a JVM is already installed on the system - with same Java requirements as the SonarQube server."

I suggest you to use an updated version of jdk 8

Can you run
Java --version
?

https://docs.sonarqube.org/latest/requirements/requirements/

They recomend use JDK and not JRE on Mac environments.

**Comment by mercuriete** [comment]
https://github.com/docker-library/openjdk/issues/77

Some libraries are missing in Alpine

**Comment by robsontenorio** [comment]
Command vendor/bin/sonar-scanner relies on jre shiped with this package or S.O one?

**Comment by rogervila** [comment]
> Command vendor/bin/sonar-scanner relies on jre shiped with this package or S.O one?

Official Sonar scanners are downloaded with the package, in the [/scanners folder](https://github.com/rogervila/php-sonarqube-scanner/tree/master/scanners)

The command unzips the necessary scanner based on your SO and executes it.

Did you try the [Test project](https://github.com/rogervila/php-sonarqube-scanner/files/3042459/sonarqube-test.zip)?  Maybe there are differences between your `Dockerfile` ad the official one from PHP.

**Comment by robsontenorio** [comment]
I will close this issue because, it is a jre/alpine/Docker issue. Not with package at all thanks for your time!

**Comment by rogervila** [comment]
Thank you for using the package! :)

If you find any other issue, do not hesitate to open it.
